# Generated by Django 5.1.4 on 2024-12-14 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=10)),
                ('residence', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slotNumber', models.IntegerField()),
                ('category', models.CharField(choices=[('P', 'PARMANENT'), ('T', 'TEMPORARY')], default='T', max_length=1)),
                ('availability', models.CharField(choices=[('A', 'AVAILABLE'), ('O', 'OCCUPIED')], default='O', max_length=1)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservationDate', models.DateField(auto_now=True)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('status', models.CharField(choices=[('P', 'PENDING'), ('C', 'COMFIRMED'), ('X', 'CENCELLED')], default='P', max_length=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Parkzoneapp.customer')),
                ('parkingLot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Parkzoneapp.parkinglot')),
            ],
        ),
    ]
