# Generated by Django 5.1.4 on 2024-12-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parkzoneapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglot',
            name='availability',
            field=models.CharField(choices=[('A', 'AVAILABLE'), ('O', 'OCCUPIED')], default='A', max_length=1),
        ),
    ]
