# Generated by Django 5.1.4 on 2025-01-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parkzoneapp', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='1234', max_length=32),
        ),
    ]
