# Generated by Django 5.1.4 on 2025-01-13 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parkzoneapp', '0004_customer_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=32),
        ),
    ]
