# Generated by Django 5.1.4 on 2025-01-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parkzoneapp', '0008_alter_payment_customer_alter_payment_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglot',
            name='availability',
            field=models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('OCCUPIED', 'OCCUPIED')], default='AVAILABLE', max_length=100),
        ),
        migrations.AlterField(
            model_name='parkinglot',
            name='category',
            field=models.CharField(choices=[('PARMANENT', 'PARMANENT'), ('TEMPORARY', 'TEMPORARY')], default='TEMPORARY', max_length=100),
        ),
    ]
