# Generated by Django 5.1.3 on 2025-02-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parkzoneapp', '0009_alter_parkinglot_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinglot',
            name='availability',
            field=models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('OCCUPIED', 'OCCUPIED'), ('RESERVED', 'RESERVED')], default='AVAILABLE', max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('COMFIRMED', 'COMFIRMED'), ('CENCELLED', 'CENCELLED')], default='P', max_length=100),
        ),
    ]
