# Generated by Django 5.2.1 on 2026-07-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Parkzoneapp', '0010_alter_parkinglot_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('COMFIRMED', 'COMFIRMED'), ('CENCELLED', 'CENCELLED')], default='PENDING', max_length=100),
        ),
    ]
